using System.Collections.Generic;

namespace AtlyssArchipelagoWIP
{
    // All data dictionaries: location IDs, quest mappings, item name mappings.
    // Separated from main plugin to keep data definitions in one place.
    public partial class AtlyssArchipelagoPlugin
    {
        // All location names mapped to index-based IDs (matches partner's Python: location_dict.index(value) + 1)
        // Order: quests (60), levels (16), merchants (60), professions (20), achievements (16) = 172 total
        public static readonly Dictionary<string, long> AllLocationNameToId = new Dictionary<string, long>
        {
            // Quests (1-60)
            { "A Warm Welcome", 1 },
            { "Communing Catacombs", 2 },
            { "Diva Must Die", 3 },
            { "The Keep Within", 4 },
            { "Tethering Grove", 5 },
            { "The Glyphik Booklet", 6 },
            { "Cleaning Terrace", 7 },
            { "Ancient Beings", 8 },
            { "Wicked Wizboars", 9 },
            { "Spiraling In The Grove", 10 },
            { "Hell In The Grove", 11 },
            { "Nulversa Magica", 12 },
            { "Finding Ammagon", 13 },
            { "The Colossus", 14 },
            { "Night Spirits", 15 },
            { "Ridding Slimes", 16 },
            { "Huntin' Hogs", 17 },
            { "Purging the Grove", 18 },
            { "Cleansing the Grove", 19 },
            { "Nulversa Viscera", 20 },
            { "Call of Fury", 21 },
            { "Mastery of Strength", 22 },
            { "Beckoning Foes", 23 },
            { "Ghostly Goods", 24 },
            { "Makin' a Mekspear", 25 },
            { "Makin' a Wizwand", 26 },
            { "Makin' a Vile Blade", 27 },
            { "Makin' a Golem Chestpiece", 28 },
            { "Makin' a Ragespear", 29 },
            { "Makin' a Monolith Chestpiece", 30 },
            { "Makin' a Firebreath Blade", 31 },
            { "Makin' a Follycannon", 32 },
            { "Summore' Spectral Powder!", 33 },
            { "Makin' More Mekspears", 34 },
            { "Makin' More Wizwands", 35 },
            { "Makin' More Vile Blades", 36 },
            { "Summore' Golem Chestpieces", 37 },
            { "Makin' More Ragespears", 38 },
            { "Summore' Monolith Chestpieces", 39 },
            { "Nulversa, Greenversa!", 40 },
            { "Summore' Firebreath Blades", 41 },
            { "Makin' More Follycannons", 42 },
            { "Focusin' in", 43 },
            { "Mastery of Dexterity", 44 },
            { "Whatta' Rush!", 45 },
            { "The Voice of Zuulneruda", 46 },
            { "Killing Tomb", 47 },
            { "Purging the Undead", 48 },
            { "Rattlecage Rage", 49 },
            { "Consumed Madness", 50 },
            { "Eradicating the Undead", 51 },
            { "Reviling the Rageboars", 52 },
            { "Gatling Galius", 53 },
            { "Reviling more Rageboars", 54 },
            { "Facing Foes", 55 },
            { "The Gall of Galius", 56 },
            { "Up and Over It", 57 },
            { "Dense Ingots", 58 },
            { "Amberite Ingots", 59 },
            { "Sapphite Ingots", 60 },

            // Levels (61-76)
            { "Reach Level 2", 61 },
            { "Reach Level 4", 62 },
            { "Reach Level 6", 63 },
            { "Reach Level 8", 64 },
            { "Reach Level 10", 65 },
            { "Reach Level 12", 66 },
            { "Reach Level 14", 67 },
            { "Reach Level 16", 68 },
            { "Reach Level 18", 69 },
            { "Reach Level 20", 70 },
            { "Reach Level 22", 71 },
            { "Reach Level 24", 72 },
            { "Reach Level 26", 73 },
            { "Reach Level 28", 74 },
            { "Reach Level 30", 75 },
            { "Reach Level 32", 76 },

            // Merchants (77-136)
            { "Buy Item #1 from Sally's Nook", 77 },
            { "Buy Item #2 from Sally's Nook", 78 },
            { "Buy Item #3 from Sally's Nook", 79 },
            { "Buy Item #4 from Sally's Nook", 80 },
            { "Buy Item #5 from Sally's Nook", 81 },
            { "Buy Item #1 from Skrit's Sikrit Market", 82 },
            { "Buy Item #2 from Skrit's Sikrit Market", 83 },
            { "Buy Item #3 from Skrit's Sikrit Market", 84 },
            { "Buy Item #4 from Skrit's Sikrit Market", 85 },
            { "Buy Item #5 from Skrit's Sikrit Market", 86 },
            { "Buy Item #1 from Frankie's Goods", 87 },
            { "Buy Item #2 from Frankie's Goods", 88 },
            { "Buy Item #3 from Frankie's Goods", 89 },
            { "Buy Item #4 from Frankie's Goods", 90 },
            { "Buy Item #5 from Frankie's Goods", 91 },
            { "Buy Item #1 from Craig's Bazzar", 92 },
            { "Buy Item #2 from Craig's Bazzar", 93 },
            { "Buy Item #3 from Craig's Bazzar", 94 },
            { "Buy Item #4 from Craig's Bazzar", 95 },
            { "Buy Item #5 from Craig's Bazzar", 96 },
            { "Buy Item #1 from Dye Merchant", 97 },
            { "Buy Item #2 from Dye Merchant", 98 },
            { "Buy Item #3 from Dye Merchant", 99 },
            { "Buy Item #4 from Dye Merchant", 100 },
            { "Buy Item #5 from Dye Merchant", 101 },
            { "Buy Item #1 from Tesh's Wares", 102 },
            { "Buy Item #2 from Tesh's Wares", 103 },
            { "Buy Item #3 from Tesh's Wares", 104 },
            { "Buy Item #4 from Tesh's Wares", 105 },
            { "Buy Item #5 from Tesh's Wares", 106 },
            { "Buy Item #1 from Nesh's Wares", 107 },
            { "Buy Item #2 from Nesh's Wares", 108 },
            { "Buy Item #3 from Nesh's Wares", 109 },
            { "Buy Item #4 from Nesh's Wares", 110 },
            { "Buy Item #5 from Nesh's Wares", 111 },
            { "Buy Item #1 from Rikko's Treasures", 112 },
            { "Buy Item #2 from Rikko's Treasures", 113 },
            { "Buy Item #3 from Rikko's Treasures", 114 },
            { "Buy Item #4 from Rikko's Treasures", 115 },
            { "Buy Item #5 from Rikko's Treasures", 116 },
            { "Buy Item #1 from Cotoo's Treasures", 117 },
            { "Buy Item #2 from Cotoo's Treasures", 118 },
            { "Buy Item #3 from Cotoo's Treasures", 119 },
            { "Buy Item #4 from Cotoo's Treasures", 120 },
            { "Buy Item #5 from Cotoo's Treasures", 121 },
            { "Buy Item #1 from Ruka's Furnace", 122 },
            { "Buy Item #2 from Ruka's Furnace", 123 },
            { "Buy Item #3 from Ruka's Furnace", 124 },
            { "Buy Item #4 from Ruka's Furnace", 125 },
            { "Buy Item #5 from Ruka's Furnace", 126 },
            { "Buy Item #1 from Torta's Fishing Shack", 127 },
            { "Buy Item #2 from Torta's Fishing Shack", 128 },
            { "Buy Item #3 from Torta's Fishing Shack", 129 },
            { "Buy Item #4 from Torta's Fishing Shack", 130 },
            { "Buy Item #5 from Torta's Fishing Shack", 131 },
            { "Buy Item #1 from Mad Statue's Gift", 132 },
            { "Buy Item #2 from Mad Statue's Gift", 133 },
            { "Buy Item #3 from Mad Statue's Gift", 134 },
            { "Buy Item #4 from Mad Statue's Gift", 135 },
            { "Buy Item #5 from Mad Statue's Gift", 136 },

            // Professions (137-156)
            { "Fishing Lv. 1", 137 },
            { "Fishing Lv. 2", 138 },
            { "Fishing Lv. 3", 139 },
            { "Fishing Lv. 4", 140 },
            { "Fishing Lv. 5", 141 },
            { "Fishing Lv. 6", 142 },
            { "Fishing Lv. 7", 143 },
            { "Fishing Lv. 8", 144 },
            { "Fishing Lv. 9", 145 },
            { "Fishing Lv. 10", 146 },
            { "Mining Lv. 1", 147 },
            { "Mining Lv. 2", 148 },
            { "Mining Lv. 3", 149 },
            { "Mining Lv. 4", 150 },
            { "Mining Lv. 5", 151 },
            { "Mining Lv. 6", 152 },
            { "Mining Lv. 7", 153 },
            { "Mining Lv. 8", 154 },
            { "Mining Lv. 9", 155 },
            { "Mining Lv. 10", 156 },

            // Achievements (157-172)
            { "A New Journey", 157 },
            { "Clearing Catacombs (1-6)", 158 },
            { "Clearing Catacombs (6-12)", 159 },
            { "Becoming a Fighter", 160 },
            { "Becoming a Mystic", 161 },
            { "Becoming a Bandit", 162 },
            { "Clearing Catacombs (12-18)", 163 },
            { "Clearing Grove (15-20)", 164 },
            { "Clearing Grove (20-25)", 165 },
            { "Judgement", 166 },
            { "Corrupted Arcana", 167 },
            { "Holier than Thou", 168 },
            { "Altered Vision", 169 },
            { "Scaling the Tower", 170 },
            { "Scaling Stars", 171 },
            { "Rude!", 172 },
        };

        // Quest names mapped to location IDs for polling (subset of AllLocationNameToId)
        private static readonly Dictionary<string, long> AllQuestToLocation = new Dictionary<string, long>
        {
            { "A Warm Welcome", 1 },
            { "Communing Catacombs", 2 },
            { "Diva Must Die", 3 },
            { "The Keep Within", 4 },
            { "Tethering Grove", 5 },
            { "The Glyphik Booklet", 6 },
            { "Cleaning Terrace", 7 },
            { "Ancient Beings", 8 },
            { "Wicked Wizboars", 9 },
            { "Spiraling In The Grove", 10 },
            { "Hell In The Grove", 11 },
            { "Nulversa Magica", 12 },
            { "Finding Ammagon", 13 },
            { "The Colossus", 14 },
            { "Night Spirits", 15 },
            { "Ridding Slimes", 16 },
            { "Huntin' Hogs", 17 },
            { "Purging the Grove", 18 },
            { "Cleansing the Grove", 19 },
            { "Nulversa Viscera", 20 },
            { "Call of Fury", 21 },
            { "Mastery of Strength", 22 },
            { "Beckoning Foes", 23 },
            { "Ghostly Goods", 24 },
            { "Makin' a Mekspear", 25 },
            { "Makin' a Wizwand", 26 },
            { "Makin' a Vile Blade", 27 },
            { "Makin' a Golem Chestpiece", 28 },
            { "Makin' a Ragespear", 29 },
            { "Makin' a Monolith Chestpiece", 30 },
            { "Makin' a Firebreath Blade", 31 },
            { "Makin' a Follycannon", 32 },
            { "Summore' Spectral Powder!", 33 },
            { "Makin' More Mekspears", 34 },
            { "Makin' More Wizwands", 35 },
            { "Makin' More Vile Blades", 36 },
            { "Summore' Golem Chestpieces", 37 },
            { "Makin' More Ragespears", 38 },
            { "Summore' Monolith Chestpieces", 39 },
            { "Nulversa, Greenversa!", 40 },
            { "Summore' Firebreath Blades", 41 },
            { "Makin' More Follycannons", 42 },
            { "Focusin' in", 43 },
            { "Mastery of Dexterity", 44 },
            { "Whatta' Rush!", 45 },
            { "The Voice of Zuulneruda", 46 },
            { "Killing Tomb", 47 },
            { "Purging the Undead", 48 },
            { "Rattlecage Rage", 49 },
            { "Consumed Madness", 50 },
            { "Eradicating the Undead", 51 },
            { "Reviling the Rageboars", 52 },
            { "Gatling Galius", 53 },
            { "Reviling more Rageboars", 54 },
            { "Facing Foes", 55 },
            { "The Gall of Galius", 56 },
            { "Up and Over It", 57 },
            { "Dense Ingots", 58 },
            { "Amberite Ingots", 59 },
            { "Sapphite Ingots", 60 },
        };

        private string GetLocationName(long locationId)
        {
            foreach (var kvp in AllLocationNameToId)
            {
                if (kvp.Value == locationId)
                    return kvp.Key;
            }
            return $"Location {locationId}";
        }

        // Removed: 6 class tomes from item pool (Fighter, Mystic, Bandit, Paladin, Magus, Bishop)
        // Removed: 9 skill scrolls from item pool (Alacrity, Sturdy, Fira, Crya, Str/Dex/Mind Mastery, Taunt, Curis)
        // UPDATED: Now includes 139 trade items (monster drops, ores, fish, special items)
        // New total: 261 items (was 191)
        public static readonly Dictionary<string, string> ItemNameMapping = new Dictionary<string, string>
        {
            // Consumables
            { "Bunbag Pack", "(lv-0) STATUSCONSUMABLE_Bunbag" },
            { "Bunjar Pack", "(lv-0) STATUSCONSUMABLE_Bunjar" },
            { "Bunpot Pack", "(lv-0) STATUSCONSUMABLE_Bunpot" },
            { "Regen Potion Pack", "(lv-10) STATUSCONSUMABLE_Regen Potion" },
            { "Regen Vial Pack", "(lv-0) STATUSCONSUMABLE_Regen Vial" },

            { "Magiclove Pack", "(lv-0) STATUSCONSUMABLE_Magiclove" },
            { "Magiflower Pack", "(lv-0) STATUSCONSUMABLE_Magiflower" },
            { "Magileaf Pack", "(lv-0) STATUSCONSUMABLE_Magileaf" },

            { "Stamstar", "(lv-0) STATUSCONSUMABLE_Stamstar" },

            { "Agility Potion Pack", "(lv-10) STATUSCONSUMABLE_Agility Potion" },
            { "Agility Vial Pack", "(lv-0) STATUSCONSUMABLE_Agility Vial" },
            { "Bolster Potion Pack", "(lv-10) STATUSCONSUMABLE_Bolster Potion" },
            { "Bolster Vial Pack", "(lv-0) STATUSCONSUMABLE_Bolster Vial" },
            { "Wisdom Potion Pack", "(lv-10) STATUSCONSUMABLE_Wisdom Potion" },
            { "Wisdom Vial Pack", "(lv-0) STATUSCONSUMABLE_Wisdom Vial" },

            { "Tome of Greater Experience", "(lv-0) STATUSCONSUMABLE_Tome of Greater Experience" },
            { "Tome of Experience", "(lv-0) STATUSCONSUMABLE_Tome of Experience" },
            { "Tome of Lesser Experience", "(lv-0) STATUSCONSUMABLE_Tome of Lesser Experience" },

            { "Carrot Cake Pack", "(lv-0) STATUSCONSUMABLE_Carrot Cake" },
            { "Minchroom Juice Pack", "(lv-0) STATUSCONSUMABLE_Minchroom Juice" },
            { "Spectral Powder Pack", "(lv-0) STATUSCONSUMABLE_Spectral Powder" },

            // Trade Items - Badges
            { "Geistlord Badge", "TRADEITEM_Geistlord Badge" },
            { "Coldgeist Badge", "TRADEITEM_Coldgeist Badge" },
            { "Earthcore Badge", "TRADEITEM_Earthcore Badge" },
            { "Windcore Badge", "TRADEITEM_Windcore Badge" },

            // Trade Items - Clusters/Ingots (existing)
            { "Iron Cluster", "TRADEITEM_Iron Cluster" },
            { "Copper Cluster", "TRADEITEM_Copper Cluster" },
            { "Mithril Cluster", "TRADEITEM_Mithril Cluster" },
            { "Dense Ingot", "TRADEITEM_Dense Ingot" },
            { "Sapphite Ingot", "TRADEITEM_Sapphite Ingot" },
            { "Amberite Ingot", "TRADEITEM_Amberite Ingot" },

            { "Soul Pearl", "TRADEITEM_Soul Pearl" },
            { "Experience Bond", "TRADEITEM_Experience Bond" },

            // Weapons - Melee (One-Handed Sword/Mace, Strength)
            { "Crypt Blade", "(lv-2) WEAPON_Crypt Blade (Sword, Strength)" },
            { "Femur Club", "(lv-2) WEAPON_Femur Club (Sword, Strength)" },
            { "Ironbark Sword", "(lv-2) WEAPON_Ironbark Sword (Sword, Strength)" },
            { "Slimecrust Blade", "(lv-2) WEAPON_Slimecrust Blade (Sword, Strength)" },
            { "Gilded Sword", "(lv-4) WEAPON_Gilded Sword (Sword, Strength)" },
            { "Splitbark Club", "(lv-4) WEAPON_Splitbark Club (Sword, Strength)" },
            { "Demicrypt Blade", "(lv-6) WEAPON_Demicrypt Blade (Sword, Strength)" },
            { "Dense Mace", "(lv-6) WEAPON_Dense Mace (Sword, Strength)" },
            { "Iron Sword", "(lv-6) WEAPON_Iron Sword (Sword, Strength)" },
            { "Dawn Mace", "(lv-8) WEAPON_Dawn Mace (Sword, Strength)" },
            { "Rude Blade", "(lv-8) WEAPON_Rude Blade (Sword, Strength)" },
            { "Vile Blade", "(lv-8) WEAPON_Vile Blade (Sword, Strength)" },
            { "Amberite Sword", "(lv-12) WEAPON_Amberite Sword (Sword, Strength)" },
            { "Nethercrypt Blade", "(lv-12) WEAPON_Nethercrypt Blade (Sword, Strength)" },
            { "Coldgeist Blade", "(lv-16) WEAPON_Coldgeist Blade (Sword, Strength)" },
            { "Mithril Sword", "(lv-16) WEAPON_Mithril Sword (Sword, Strength)" },
            { "Serrated Blade", "(lv-16) WEAPON_Serrated Blade (Sword, Strength)" },
            { "Nulrok Mace", "(lv-20) WEAPON_Nulrok Mace (Sword, Strength)" },
            { "Firebreath Blade", "(lv-22) WEAPON_Firebreath Blade (Sword, Strength)" },
            { "Valdur Blade", "(lv-24) WEAPON_Valdur Blade (Sword, Strength)" },
            { "Fier Blade", "(lv-26) WEAPON_Fier Blade (Sword, Strength)" },

            // Weapons - Hammers (Two-Handed Heavy Melee, Strength)
            { "Slimek Axehammer", "(lv-4) WEAPON_Slimek Axehammer (Hammer, Strength)" },
            { "Dense Hammer", "(lv-6) WEAPON_Dense Hammer (Hammer, Strength)" },
            { "Iron Axehammer", "(lv-6) WEAPON_Iron Axehammer (Hammer, Strength)" },
            { "Crypt Pounder", "(lv-8) WEAPON_Crypt Pounder (Hammer, Strength)" },
            { "Quake Pummeler", "(lv-18) WEAPON_Quake Pummeler (Hammer, Strength)" },

            // Weapons - Greatblades (Two-Handed Heavy Melee, Strength)
            { "Mini Geist Scythe", "(lv-4) WEAPON_Mini Geist Scythe (Greatblade, Strength)" },
            { "Geist Scythe", "(lv-6) WEAPON_Geist Scythe (Greatblade, Strength)" },
            { "Stone Greatblade", "(lv-8) WEAPON_Stone Greatblade (Greatblade, Strength)" },
            { "Amberite Warstar", "(lv-12) WEAPON_Amberite Warstar (Greatblade, Strength)" },
            { "Dolkin's Axe", "(lv-12) WEAPON_Dolkin's Axe (Greatblade, Strength)" },
            { "Poltergeist Scythe", "(lv-14) WEAPON_Poltergeist Scythe (Greatblade, Strength)" },
            { "Coldgeist Punisher", "(lv-16) WEAPON_Coldgeist Punisher (Greatblade, Strength)" },
            { "Deadwood Axe", "(lv-16) WEAPON_Deadwood Axe (Greatblade, Strength)" },
            { "Mithril Greatsword", "(lv-16) WEAPON_Mithril Greatsword (Greatblade, Strength)" },
            { "Deathknight Runeblade", "(lv-22) WEAPON_Deathknight Runeblade (Greatblade, Strength)" },
            { "Ryzer Greataxe", "(lv-26) WEAPON_Ryzer Greataxe (Greatblade, Strength)" },

            // Weapons - Polearms (Two-Handed, Strength)
            { "Dense Spear", "(lv-6) WEAPON_Dense Spear (Polearm, Strength)" },
            { "Iron Spear", "(lv-6) WEAPON_Iron Spear (Polearm, Strength)" },
            { "Cryptsinge Halberd", "(lv-8) WEAPON_Cryptsinge Halberd (Polearm, Strength)" },
            { "Mekspear", "(lv-8) WEAPON_Mekspear (Polearm, Strength)" },
            { "Amberite Halberd", "(lv-12) WEAPON_Amberite Halberd (Polearm, Strength)" },
            { "Necroroyal Halberd", "(lv-12) WEAPON_Necroroyal Halberd (Polearm, Strength)" },
            { "Sinner Bardiche", "(lv-12) WEAPON_Sinner Bardiche (Polearm, Strength)" },
            { "Mithril Halberd", "(lv-16) WEAPON_Mithril Halberd (Polearm, Strength)" },
            { "Ragespear", "(lv-16) WEAPON_Ragespear (Polearm, Strength)" },
            { "Serrated Spear", "(lv-16) WEAPON_Serrated Spear (Polearm, Strength)" },
            { "Sapphite Spear", "(lv-18) WEAPON_Sapphite Spear (Polearm, Strength)" },
            { "Nulrok Spear", "(lv-20) WEAPON_Nulrok Spear (Polearm, Strength)" },
            { "Cyrotribe Spear", "(lv-22) WEAPON_Cryotribe Spear (Polearm, Strength)" },
            { "Flametribe Spear", "(lv-22) WEAPON_Flametribe Spear (Polearm, Strength)" },

            // Weapons - Scepters (One-Handed, Mind)
            { "Marrow Bauble", "(lv-2) WEAPON_Marrow Bauble (Scepter, Mind)" },
            { "Splitbark Scepter", "(lv-2) WEAPON_Splitbark Scepter (Scepter, Mind)" },
            { "Demicrypt Bauble", "(lv-6) WEAPON_Demicrypt Bauble (Scepter, Mind)" },
            { "Iron Scepter", "(lv-6) WEAPON_Iron Scepter (Scepter, Mind)" },
            { "Cryo Cane", "(lv-8) WEAPON_Cryo Cane (Scepter, Mind)" },
            { "Slime Diva Baton", "(lv-8) WEAPON_Slime Diva Baton (Scepter, Mind)" },
            { "Pyre Cane", "(lv-12) WEAPON_Pyre Cane (Scepter, Mind)" },
            { "Wizwand", "(lv-12) WEAPON_Wizwand (Scepter, Mind)" },
            { "Nethercrypt Bauble", "(lv-14) WEAPON_Nethercrypt Bauble (Scepter, Mind)" },
            { "Aquapetal Staff", "(lv-16) WEAPON_Aquapetal Staff (Scepter, Mind)" },
            { "Flamepetal Staff", "(lv-16) WEAPON_Flamepetal Staff (Scepter, Mind)" },
            { "Mithril Scepter", "(lv-16) WEAPON_Mithril Scepter (Scepter, Mind)" },
            { "Sapphite Scepter", "(lv-18) WEAPON_Sapphite Scepter (Scepter, Mind)" },
            { "Voalstark Wand", "(lv-24) WEAPON_Voalstark Wand (Scepter, Mind)" },

            // Weapons - Bells (Two-Handed, Mind)
            { "Cryptcall Bell", "(lv-8) WEAPON_Cryptcall Bell (Magic Bell, Mind)" },
            { "Iron Bell", "(lv-8) WEAPON_Iron Bell (Magic Bell, Mind)" },
            { "Coldgeist Frostcaller", "(lv-16) WEAPON_Coldgeist Frostcaller (Magic Bell, Mind)" },
            { "Mithril Bell", "(lv-16) WEAPON_Mithril Bell (Magic Bell, Mind)" },
            { "Colossus Tone", "(lv-18) WEAPON_Colossus Tone (Magic Bell, Mind)" },
            { "Sapphite Bell", "(lv-18) WEAPON_Sapphite Bell (Magic Bell, Mind)" },

            // Weapons - Katars (Two-Handed, Dexterity)
            { "Sliemcrust Katars", "(lv-2) WEAPON_Slimecrust Katars (Katars, Dexterity)" },
            { "Cryptsinge Katars", "(lv-4) WEAPON_Cryptsinge Katars (Katars, Dexterity)" },
            { "Slimek Shivs", "(lv-4) WEAPON_Slimek Shivs (Katars, Dexterity)" },
            { "Deathgel Shivs", "(lv-6) WEAPON_Deathgel Shivs (Katars, Dexterity)" },
            { "Dense Katars", "(lv-6) WEAPON_Dense Katars (Katars, Dexterity)" },
            { "Iron Katars", "(lv-8) WEAPON_Iron Katars (Katars, Dexterity)" },
            { "Runic Katars", "(lv-10) WEAPON_Runic Katars (Katars, Dexterity)" },
            { "Geistlord Claws", "(lv-12) WEAPON_Geistlord Claws (Katars, Dexterity)" },
            { "Hellsludge Shivs", "(lv-14) WEAPON_Hellsludge Shivs (Katars, Dexterity)" },
            { "Mithril Katars", "(lv-14) WEAPON_Mithril Katars (Katars, Dexterity)" },
            { "Frostbite Claws", "(lv-16) WEAPON_Frostbite Claws (Katars, Dexterity)" },
            { "Serrated Knuckles", "(lv-16) WEAPON_Serrated Knuckles (Katars, Dexterity)" },
            { "Rummok Bladerings", "(lv-18) WEAPON_Rummok Bladerings (Katars, Dexterity)" },
            { "Sapphite Katars", "(lv-18) WEAPON_Sapphite Katars (Katars, Dexterity)" },
            { "Golemfist Katars", "(lv-20) WEAPON_Golemfist Katars (Katars, Dexterity)" },

            // Weapons - Bows (Two-Handed Ranged, Dexterity)
            { "Crypt Bow", "(lv-2) WEAPON_Crypt Bow (Bow, Dexterity)" },
            { "Demicrypt Bow", "(lv-6) WEAPON_Demicrypt Bow (Bow, Dexterity)" },
            { "Iron Bow", "(lv-6) WEAPON_Iron Bow (Bow, Dexterity)" },
            { "Mekspike Bow", "(lv-8) WEAPON_Mekspike Bow (Bow, Dexterity)" },
            { "Menace Bow", "(lv-8) WEAPON_Menace Bow (Bow, Dexterity)" },
            { "Petrified Bow", "(lv-12) WEAPON_Petrified Bow (Bow, Dexterity)" },
            { "Mithril Bow", "(lv-14) WEAPON_Mithril Bow (Bow, Dexterity)" },
            { "Necroroyal Bow", "(lv-14) WEAPON_Necroroyal Bow (Bow, Dexterity)" },
            { "Colgeist Bow", "(lv-16) WEAPON_Coldgeist Bow (Bow, Dexterity)" },
            { "Serrated Longbow", "(lv-16) WEAPON_Serrated Longbow (Bow, Dexterity)" },
            { "Torrentius Longbow", "(lv-24) WEAPON_Torrentius Longbow (Bow, Dexterity)" },

            // Weapons - Shotguns (Two-Handed Ranged, Dexterity)
            { "Amberite Boomstick", "(lv-12) WEAPON_Amberite Boomstick (Shotgun, Dexterity)" },
            { "Magitek Burstgun", "(lv-20) WEAPON_Magitek Burstgun (Shotgun, Dexterity)" },
            { "Follycannon", "(lv-26) WEAPON_Follycannon (Shotgun, Dexterity)" },

            // Armor - Helms
            { "Agility Ears", "(lv-1) HELM_Agility Ears" },
            { "Festive Hat", "(lv-1) HELM_Festive Hat" },
            { "Fishin Hat", "(lv-1) HELM_Fishin Hat" },
            { "Leather Cap", "(lv-1) HELM_Leather Cap" },
            { "Newfold Halo", "(lv-1) HELM_Newfold Halo" },
            { "Orefinder Hat", "(lv-1) HELM_Orefinder Hat" },
            { "Spooky Hat", "(lv-1) HELM_Spooky Hat" },
            { "Top Hat", "(lv-1) HELM_Top Hat" },
            { "Wizard Hat", "(lv-1) HELM_Wizard Hat" },
            { "Acolyte Hood", "(lv-4) HELM_Acolyte Hood" },
            { "Cryptsinge Halo", "(lv-4) HELM_Cryptsinge Halo" },
            { "Initial Spectacles", "(lv-4) HELM_Initiate Spectacles" },
            { "Demicrypt Halo", "(lv-6) HELM_Demicrypt Halo" },
            { "Desne Helm", "(lv-6) HELM_Dense Helm" },
            { "Diva Crown", "(lv-6) HELM_Diva Crown" },
            { "Iron Halo", "(lv-6) HELM_Iron Halo" },
            { "Necromancer Hood", "(lv-8) HELM_Necromancer Hood" },
            { "Geistlord Crown", "(lv-10) HELM_Geistlord Crown" },
            { "Journeyman Spectacles", "(lv-10) HELM_Journeyman Spectacles" },
            { "Amberite Helm", "(lv-12) HELM_Amberite Helm" },
            { "Focus Circlet", "(lv-12) HELM_Focus Circlet" },
            { "Magistrate Circlet", "(lv-12) HELM_Magistrate Circlet" },
            { "Rage Circlet", "(lv-12) HELM_Rage Circlet" },
            { "Focusi Glasses", "(lv-14) HELM_Focusi Glasses" },
            { "Nethercrypt Halo", "(lv-14) HELM_Nethercrypt Halo" },
            { "Carbuncle Hat", "(lv-16) HELM_Carbuncle Hat" },
            { "Geistlord Eye", "(lv-16) HELM_Geistlord Eye" },
            { "Glyphgrift Halo", "(lv-16) HELM_Glyphgrift Halo" },
            { "Jestercast Memory", "(lv-16) HELM_Jestercast Memory" },
            { "Knightguard Halo", "(lv-16) HELM_Knightguard Halo" },
            { "Mithril Halo", "(lv-16) HELM_Mithril Halo" },
            { "Sapphite Mindhat", "(lv-18) HELM_Sapphite Mindhat" },
            { "Dire Helm", "(lv-22) HELM_Dire Helm" },
            { "Druidic Halo", "(lv-22) HELM_Druidic Halo" },
            { "Guardel Helm", "(lv-22) HELM_Guardel Helm" },
            { "Leathen Cap", "(lv-22) HELM_Leathen Cap" },
            { "Boarus Helm", "(lv-24) HELM_Boarus Helm" },
            { "Deathknight Helm", "(lv-24) HELM_Deathknight Helm" },
            { "Emerock Halo", "(lv-24) HELM_Emerock Halo" },
            { "Wizlad Hood", "(lv-24) HELM_Wizlad Hood" },
            { "Boarus Torment", "(lv-26) HELM_Boarus Torment" },

            // Armor - Capes
            { "Initiate Cloak", "(lv-2) CAPE_Initiate Cloak" },
            { "Slimewoven Cloak", "(lv-4) CAPE_Slimewoven Cloak" },
            { "Nokket Cloak", "(lv-6) CAPE_Nokket Cloak" },
            { "Rugged Cloak", "(lv-6) CAPE_Rugged Cloak" },
            { "Regazuul Cape", "(lv-10) CAPE_Regazuul Cape" },
            { "Flux Cloak", "(lv-12) CAPE_Flux Cloak" },
            { "Cozy Cloak", "(lv-14) CAPE_Cozy Cloak" },
            { "Nethercrypt Cloak", "(lv-14) CAPE_Nethercrypt Cloak" },
            { "Cobblerage Cloak", "(lv-16) CAPE_Cobblerage Cloak" },
            { "Deathward Cape", "(lv-16) CAPE_Deathward Cape" },
            { "Forlorn Cloak", "(lv-16) CAPE_Forlorn Cloak" },
            { "Meshlink Cape", "(lv-16) CAPE_Meshlink Cape" },
            { "Sagecaller Cape", "(lv-16) CAPE_Sagecaller Cape" },
            { "Roudon Cape", "(lv-18) CAPE_Roudon Cape" },
            { "Blueversa Cape", "(lv-20) CAPE_Blueversa Cape" },
            { "Greenversa Cape", "(lv-20) CAPE_Greenversa Cape" },
            { "Nulversa Cape", "(lv-20) CAPE_Nulversa Cape" },
            { "Redversa Cape", "(lv-20) CAPE_Redversa Cape" },
            { "Windgolem Cloak", "(lv-22) CAPE_Windgolem Cloak" },
            { "Mekwar Drape", "(lv-24) CAPE_Mekwar Drape" },

            // Armor - Chestpieces
            { "Aero Top", "(lv-1) CHESTPIECE_Aero Top" },
            { "Bunhost Garb", "(lv-1) CHESTPIECE_Bunhost Garb" },
            { "Festive Coat", "(lv-1) CHESTPIECE_Festive Coat" },
            { "Fisher Overalls", "(lv-1) CHESTPIECE_Fisher Overalls" },
            { "Leather Top", "(lv-1) CHESTPIECE_Leather Top" },
            { "Necro Marrow", "(lv-1) CHESTPIECE_Necro Marrow" },
            { "Noble Shirt", "(lv-1) CHESTPIECE_Noble Shirt" },
            { "Nutso Top", "(lv-1) CHESTPIECE_Nutso Top" },
            { "Orefinder Vest", "(lv-1) CHESTPIECE_Orefinder Vest" },
            { "Ritualist Garb", "(lv-1) CHESTPIECE_Ritualist Garb" },
            { "Sagecloth Top", "(lv-1) CHESTPIECE_Sagecloth Top" },
            { "Silken Top", "(lv-1) CHESTPIECE_Silken Top" },
            { "Spooky Garment", "(lv-1) CHESTPIECE_Spooky Garment" },
            { "Vampiric Coat", "(lv-1) CHESTPIECE_Vampiric Coat" },
            { "Ghostly Tabard", "(lv-2) CHESTPIECE_Ghostly Tabard" },
            { "Poacher Cloth", "(lv-2) CHESTPIECE_Poacher Cloth" },
            { "Ragged Shirt", "(lv-2) CHESTPIECE_Ragged Shirt" },
            { "Slimecrust Chest", "(lv-2) CHESTPIECE_Slimecrust Chest" },
            { "Worn Robe", "(lv-2) CHESTPIECE_Worn Robe" },
            { "Cryptsinge Chest", "(lv-4) CHESTPIECE_Cryptsinge Chest" },
            { "Journeyman Vest", "(lv-4) CHESTPIECE_Journeyman Vest" },
            { "Slimek Chest", "(lv-4) CHESTPIECE_Slimek Chest" },
            { "Dense Chestpiece", "(lv-6) CHESTPIECE_Dense Chestpiece" },
            { "Trodd Tunic", "(lv-6) CHESTPIECE_Trodd Tunic" },
            { "Iron Chestplate", "(lv-7) CHESTPIECE_Iron Chestpiece" },
            { "Tattered Battlerobe", "(lv-8) CHESTPIECE_Tattered Battlerobe" },
            { "Apprentice Robe", "(lv-10) CHESTPIECE_Apprentice Robe" },
            { "Duelist Garb", "(lv-10) CHESTPIECE_Duelist Garb" },
            { "Skywrill Tabard", "(lv-10) CHESTPIECE_Skywrill Tabard" },
            { "Sleeper's Robe", "(lv-10) CHESTPIECE_Sleeper's Robe" },
            { "Warrior Chest", "(lv-10) CHESTPIECE_Warrior Chest" },
            { "Amberite Breastplate", "(lv-12) CHESTPIECE_Amberite Breastplate" },
            { "Golem Chestpiece", "(lv-12) CHESTPIECE_Golem Chestpiece" },
            { "Lord Breastplate", "(lv-12) CHESTPIECE_Lord Breastplate" },
            { "Nethercrypt Tabard", "(lv-12) CHESTPIECE_Nethercrypt Tabard" },
            { "Reapsow Garb", "(lv-12) CHESTPIECE_Reapsow Garb" },
            { "Witchlock Robe", "(lv-12) CHESTPIECE_Witchlock Robe" },
            { "Chainmail Guard", "(lv-14) CHESTPIECE_Chainmail Guard" },
            { "Ornamented Battlerobe", "(lv-14) CHESTPIECE_Ornamented Battlerobe" },
            { "Carbuncle Robe", "(lv-16) CHESTPIECE_Carbuncle Robe" },
            { "Chainscale Chest", "(lv-16) CHESTPIECE_Chainscale Chest" },
            { "Gemveil Raiment", "(lv-16) CHESTPIECE_Gemveil Raiment" },
            { "King Breastplate", "(lv-16) CHESTPIECE_King Breastplate" },
            { "Mercenary Vestment", "(lv-16) CHESTPIECE_Mercenary Vestment" },
            { "Mithril Chestpiece", "(lv-16) CHESTPIECE_Mithril Chestpiece" },
            { "Reaper Gi", "(lv-16) CHESTPIECE_Reaper Gi" },
            { "Witchwizard Robe", "(lv-16) CHESTPIECE_Witchwizard Robe" },
            { "Berserker Chestpiece", "(lv-18) CHESTPIECE_Berserker Chestpiece" },
            { "Fuguefall Duster", "(lv-18) CHESTPIECE_Fuguefall Duster" },
            { "Magilord Overalls", "(lv-18) CHESTPIECE_Magilord Overalls" },
            { "Monolith Chestpiece", "(lv-18) CHESTPIECE_Monolith Chestpiece" },
            { "Sapphite Guard", "(lv-18) CHESTPIECE_Sapphite Guard" },
            { "Druidic Robe", "(lv-20) CHESTPIECE_Druidic Robe" },
            { "Emerock Chestpiece", "(lv-20) CHESTPIECE_Emerock Chestpiece" },
            { "Fortified Chestpiece", "(lv-20) CHESTPIECE_Fortified Vestment" },
            { "Roudon Chestpiece", "(lv-20) CHESTPIECE_Roudon Chestpiece" },
            { "Earthbind Tabard", "(lv-22) CHESTPIECE_Earthbind Tabard" },
            { "Gemveil Breastplate", "(lv-22) CHESTPIECE_Gemveil Breastplate" },
            { "Roudon Robe", "(lv-22) CHESTPIECE_Roudon Robe" },
            { "Ruggrok Vest", "(lv-22) CHESTPIECE_Ruggrok Vest" },
            { "Excecutioner Vestment", "(lv-24) CHESTPIECE_Executioner Vestment" },
            { "Fender Garb", "(lv-24) CHESTPIECE_Fender Garb" },
            { "Wizlad Robe", "(lv-24) CHESTPIECE_Wizlad Robe" },

            // Armor - Leggings
            { "Aero Pants", "(lv-1) LEGGINGS_Aero Pants" },
            { "Bunhost Leggings", "(lv-1) LEGGINGS_Bunhost Leggings" },
            { "Festive Trouser", "(lv-1) LEGGINGS_Festive Trousers" },
            { "Leather Britches", "(lv-1) LEGGINGS_Leather Britches" },
            { "Necro Caustics", "(lv-1) LEGGINGS_Necro Caustics" },
            { "Noble Pants", "(lv-1) LEGGINGS_Noble Pants" },
            { "Nutso Pants", "(lv-1) LEGGINGS_Nutso Pants" },
            { "Orefinder", "(lv-1) LEGGINGS_Orefinder Trousers" },
            { "Ritualist Straps", "(lv-1) LEGGINGS_Ritualist Straps" },
            { "Sagecloth Shorts", "(lv-1) LEGGINGS_Sagecloth Shorts" },
            { "Silken Loincloth", "(lv-1) LEGGINGS_Silken Loincloth" },
            { "Vampiric Leggings", "(lv-1) LEGGINGS_Vampiric Leggings" },
            { "Ghostly Legwraps", "(lv-2) LEGGINGS_Ghostly Legwraps" },
            { "Journeyman Shorts", "(lv-2) LEGGINGS_Journeyman Shorts" },
            { "Slimecrust Leggings", "(lv-2) LEGGINGS_Slimecrust Leggings" },
            { "Journeyman Leggings", "(lv-4) LEGGINGS_Journeyman Leggings" },
            { "Slimek Leggings", "(lv-4) LEGGINGS_Slimek Leggings" },
            { "Dense Leggings", "(lv-6) LEGGINGS_Dense Leggings" },
            { "Sash Leggings", "(lv-8) LEGGINGS_Sash Leggings" },
            { "Warrior Leggings", "(lv-10) LEGGINGS_Warrior Leggings" },
            { "Amberite Leggings", "(lv-12) LEGGINGS_Amberite Leggings" },
            { "Chainmail Leggings", "(lv-12) LEGGINGS_Chainmail Leggings" },
            { "Darkcloth Pants", "(lv-12) LEGGINGS_Darkcloth Pants" },
            { "Lord Greaves", "(lv-12) LEGGINGS_Lord Greaves" },
            { "Reapsow Pants", "(lv-12) LEGGINGS_Reapsow Pants" },
            { "Witchlock Loincloth", "(lv-12) LEGGINGS_Witchlock Loincloth" },
            { "King Greaves", "(lv-16) LEGGINGS_King Greaves" },
            { "Mercenary Leggings", "(lv-16) LEGGINGS_Mercenary Leggings" },
            { "Reaper Leggings", "(lv-16) LEGGINGS_Reaper Leggings" },
            { "Stridebond Pants", "(lv-16) LEGGINGS_Stridebond Pants" },
            { "Witchwizard Garterbelt", "(lv-16) LEGGINGS_Witchwizard Garterbelt" },
            { "Berserker Leggings", "(lv-18) LEGGINGS_Berserker Leggings" },
            { "Fuguefall Pants", "(lv-18) LEGGINGS_Fuguefall Pants" },
            { "Magilord Boots", "(lv-18) LEGGINGS_Magilord Boots" },
            { "Sapphite Leggings", "(lv-18) LEGGINGS_Sapphite Leggings" },
            { "Jadewall Trousers", "(lv-20) LEGGINGS_Jadewail Trousers" },
            { "Temrak Britches", "(lv-20) LEGGINGS_Temrak Britches" },
            { "Eschek Greaves", "(lv-22) LEGGINGS_Eschek Greaves" },
            { "Gemveil Leggings", "(lv-22) LEGGINGS_Gemveil Leggings" },
            { "Executioner Leggings", "(lv-24) LEGGINGS_Executioner Leggings" },
            { "Fender Leggings", "(lv-24) LEGGINGS_Fender Leggings" },

            // Armor - Shields
            { "Wooden Shield", "(lv-1) SHIELD_Wooden Shield" },
            { "Crypt Buckler", "(lv-4) SHIELD_Crypt Buckler" },
            { "Slimek Shield", "(lv-4) SHIELD_Slimek Shield" },
            { "Demicrypt Buckler", "(lv-6) SHIELD_Demicrypt Buckler" },
            { "Dense Shield", "(lv-6) SHIELD_Dense Shield" },
            { "Iron Shield", "(lv-6) SHIELD_Iron Shield" },
            { "Iris Shield", "(lv-8) SHIELD_Iris Shield" },
            { "Omen Shield", "(lv-8) SHIELD_Omen Shield" },
            { "Amberite Shield", "(lv-12) SHIELD_Amberite Shield" },
            { "Slabton Shield", "(lv-12) SHIELD_Slabton Shield" },
            { "Mithril Shield", "(lv-14) SHIELD_Mithril Shield" },
            { "Nethercrypt Shield", "(lv-14) SHIELD_Nethercrypt Shield" },
            { "Rustweary Shield", "(lv-16) SHIELD_Rustweary Shield" },
            { "Rustwise Shield", "(lv-16) SHIELD_Rustwise Shield" },
            { "Sapphite Shield", "(lv-18) SHIELD_Sapphite Shield" },
            { "Rigor Buckler", "(lv-20) SHIELD_Rigor Buckler" },
            { "Daemon Shield", "(lv-22) SHIELD_Daemon Shield" },
            { "Irisun Shield", "(lv-22) SHIELD_Irisun Shield" },

            // Accessories - Trinkets (Rings)
            { "Old Ring", "(lv-1) RING_Old Ring" },
            { "Ring of Ambition", "(lv-1) RING_Ring Of Ambition" },
            { "Nograd's Amulet", "(lv-2) RING_Nograd's Amulet" },
            { "The One Ring", "(lv-2) RING_The One Ring" },
            { "Ambersquire Ring", "(lv-6) RING_Ambersquire Ring" },
            { "Emeraldfocus Ring", "(lv-6) RING_Emeraldfocus Ring" },
            { "Sapphireweave Ring", "(lv-6) RING_Sapphireweave Ring" },
            { "Edon's Pendant", "(lv-8) RING_Edon's Pendant" },
            { "Geistlord Ring", "(lv-12) RING_Geistlord Ring" },
            { "Students Ring", "(lv-12) RING_Students Ring" },
            { "Pearlpond Ring", "(lv-14) RING_Pearlpond Ring" },
            { "Slitherwraith Ring", "(lv-14) RING_Slitherwraith Ring" },
            { "Geistlord Band", "(lv-16) RING_Geistlord Band" },
            { "Jadetrout Ring", "(lv-16) RING_Jadetrout Ring" },
            { "Orbos Ring", "(lv-16) RING_Orbos Ring" },
            { "Valor Ring", "(lv-16) RING_Valor Ring" },
            { "Earthwoken Ring", "(lv-18) RING_Earthwoken Ring" },
            { "Noji Talisman", "(lv-20) RING_Noji Talisman" },
            { "Valdur Effigy", "(lv-24) RING_Valdur Effigy" },
            { "Glyphik Booklet", "(lv-26) RING_Glyphik Booklet" },
            { "Tessellated Drive", "(lv-26) RING_Tessellated Drive" },

            // NEW: Trade Items - Monster Drops (139 items added)
            { "Aqua Muchroom Cap", "TRADEITEM_Aqua Muchroom Cap" },
            { "Barknaught Face", "TRADEITEM_Barknaught Face" },
            { "Blightwood Log", "TRADEITEM_Blightwood Log" },
            { "Blightwood Stick", "TRADEITEM_Blightwood Stick" },
            { "Blue Minchroom Cap", "TRADEITEM_Blue Minchroom Cap" },
            { "Boomboar Gear", "TRADEITEM_Boomboar Gear" },
            { "Boomboar Head", "TRADEITEM_Boomboar Head" },
            { "Boomboar Pouch", "TRADEITEM_Boomboar Pouch" },
            { "Burnrose", "TRADEITEM_Burnrose" },
            { "Carbuncle Foot", "TRADEITEM_Carbuncle Foot" },
            { "Cursed Note", "TRADEITEM_Cursed Note" },
            { "Deadwood Log", "TRADEITEM_Deadwood Log" },
            { "Deathgel Core", "TRADEITEM_Deathgel Core" },
            { "Deathknight Gauntlet", "TRADEITEM_Deathknight Gauntlet" },
            { "Demigolem Core", "TRADEITEM_Demigolem Core" },
            { "Demigolem Gem", "TRADEITEM_Demigolem Gem" },
            { "Diva Necklace", "TRADEITEM_Diva Necklace" },
            { "Firebreath Gland", "TRADEITEM_Firebreath Gland" },
            { "Fluxfern", "TRADEITEM_Fluxfern" },
            { "Gale Muchroom Cap", "TRADEITEM_Gale Muchroom Cap" },
            { "Geist Collar", "TRADEITEM_Geist Collar" },
            { "Ghostdust", "TRADEITEM_Ghostdust" },
            { "Golem Core", "TRADEITEM_Golem Core" },
            { "Golem Gem", "TRADEITEM_Golem Gem" },
            { "Green Lipstick", "TRADEITEM_Green Lipstick" },
            { "Hellsludge Core", "TRADEITEM_Hellsludge Core" },
            { "Maw Eye", "TRADEITEM_Maw Eye" },
            { "Mekboar Head", "TRADEITEM_Mekboar Head" },
            { "Mekboar Spear", "TRADEITEM_Mekboar Spear" },
            { "Monolith Core", "TRADEITEM_Monolith Core" },
            { "Monolith Gem", "TRADEITEM_Monolith Gem" },
            { "Mouth Bittertooth", "TRADEITEM_Mouth Bittertooth" },
            { "Mouth Eye", "TRADEITEM_Mouth Eye" },
            { "Rageboar Head", "TRADEITEM_Rageboar Head" },
            { "Rageboar Spear", "TRADEITEM_Rageboar Spear" },
            { "Red Minchroom Cap", "TRADEITEM_Red Minchroom Cap" },
            { "Rock", "TRADEITEM_Rock" },
            { "Slime Core", "TRADEITEM_Slime Core" },
            { "Slime Diva Ears", "TRADEITEM_Slime Diva Ears" },
            { "Slime Ears", "TRADEITEM_Slime Ears" },
            { "Slimek Core", "TRADEITEM_Slimek Core" },
            { "Slimek Ears", "TRADEITEM_Slimek Ears" },
            { "Slimek Eye", "TRADEITEM_Slimek Eye" },
            { "Vinethorn", "TRADEITEM_Vinethorn" },
            { "Vout Antennae", "TRADEITEM_Vout Antennae" },
            { "Vout Wing", "TRADEITEM_Vout Wing" },
            { "Warboar Axe", "TRADEITEM_Warboar Axe" },
            { "Warboar Head", "TRADEITEM_Warboar Head" },
            { "Wizboar Head", "TRADEITEM_Wizboar Head" },
            { "Wizboar Scepter", "TRADEITEM_Wizboar Scepter" },

            // Trade Items - Ores (raw materials)
            { "Amberite Ore", "TRADEITEM_Amberite Ore" },
            { "Dense Ore", "TRADEITEM_Dense Ore" },
            { "Sapphite Ore", "TRADEITEM_Sapphite Ore" },
            { "Coal", "TRADEITEM_Coal" },

            // NEW: Trade Items - Fish
            { "Big Wan", "TRADEITEM_Big Wan" },
            { "Bittering Katfish", "TRADEITEM_Bittering Katfish" },
            { "Bonefish", "TRADEITEM_Bonefish" },
            { "Smiling Wrellfish", "TRADEITEM_Smiling Wrellfish" },
            { "Squangfish", "TRADEITEM_Squangfish" },
            { "Sugeel", "TRADEITEM_Sugeel" },
            { "Sugshrimp", "TRADEITEM_Sugshrimp" },
            { "Windtail Fish", "TRADEITEM_Windtail Fish" },
            { "Old Boot", "TRADEITEM_Old Boot" },

            // NEW: Trade Items - Special Stones/Gems
            { "Agility Stone", "TRADEITEM_Agility Stone" },
            { "Angela's Tear", "TRADEITEM_Angela's Tear" },
            { "Epic Carrot", "TRADEITEM_Epic Carrot" },
            { "Flux Stone", "TRADEITEM_Flux Stone" },
            { "Illusion Stone", "TRADEITEM_Illusion Stone" },
            { "Might Stone", "TRADEITEM_Might Stone" },
            { "Starlight Gem", "TRADEITEM_Starlight Gem" },

            // Dyes - filler items
            { "Black Dye", "TRADEITEM_Black Dye" },
            { "Blue Dye", "TRADEITEM_Blue Dye" },
            { "Brown Dye", "TRADEITEM_Brown Dye" },
            { "Cyan Dye", "TRADEITEM_Cyan Dye" },
            { "Green Dye", "TRADEITEM_Green Dye" },
            { "Grey Dye", "TRADEITEM_Grey Dye" },
            { "Lime Dye", "TRADEITEM_Lime Dye" },
            { "Orange Dye", "TRADEITEM_Orange Dye" },
            { "Pink Dye", "TRADEITEM_Pink Dye" },
            { "Purple Dye", "TRADEITEM_Purple Dye" },
            { "Red Dye", "TRADEITEM_Red Dye" },
            { "White Dye", "TRADEITEM_White Dye" },
            { "Yellow Dye", "TRADEITEM_Yellow Dye" },

            // Crowns - currency filler (given as gold directly)
            { "Crowns (Small)", "CURRENCY_250" },
            { "Crowns (Medium)", "CURRENCY_500" },
            { "Crowns (Large)", "CURRENCY_1000" },
            { "Crowns (Huge)", "CURRENCY_2500" },

            // Tomes - useful items
            { "Tome of Naivety", "(lv-0) STATUSCONSUMABLE_Tome of Naivety" },
            { "Tome of Unlearning", "(lv-0) STATUSCONSUMABLE_Tome of Unlearning" },

            // Wood-tier starter weapons
            { "Wood Sword", "(lv-0) WEAPON_Wood Sword (Sword, Strength)" },
            { "Wood Hammer", "(lv-0) WEAPON_Wood Hammer (Hammer, Strength)" },
            { "Wood Spear", "(lv-0) WEAPON_Wood Spear (Spear, Strength)" },
            { "Wood Scepter", "(lv-0) WEAPON_Wood Scepter (Scepter, Mind)" },
            { "Wood Daggers", "(lv-0) WEAPON_Wood Daggers (Daggers, Dexterity)" },
            { "Wooden Bell", "(lv-0) WEAPON_Wooden Bell (Bell, Mind)" },
            { "Wooden Bow", "(lv-0) WEAPON_Wooden Bow (Bow, Dexterity)" },

            // Test items - filler
            { "Test Chestpiece", "(lv-1) CHESTPIECE_Test Chestpiece" },
            { "Test Pants", "(lv-1) LEGGINGS_Test Pants" },
            { "Test Ring", "(lv-1) RING_Test Ring" },
        };
    }
}